### ISSUE TITLE
Switch to Github Actions to publish the Page

### ISSUE THREAD

**Issue by vikhik** [PLAYERUNKNOWN-Productions/preface-globe-navigator#2]
Currently, we use a branch to host the page, so we can include our npm dependencies.

It would be better if we use GitHub Actions, but we didn't have time to experiment with this.

**Comment by PPPNAK** [comment]
implemented since [this commit](https://github.com/PLAYERUNKNOWN-Productions/preface-globe-navigator/commit/e6bf1980a2d4b57295491c71b124129729bb24ce)
